Add Initial tables
turbot/steampipe-plugin-azuredevops pull request #1
Opened 2023-04-17 15:32 UTC by bigdatasourav

2023-05-18 14:47 UTC, madhushreeray30 requested changes
Please have a look at the comments. Thanks!

2023-05-22 06:45 UTC, bigdatasourav commented on azuredevops/table_azuredevops_user.go
> +				Description: "This field identifies the type of the graph subject (ex: User, Scope, User).",
Updated.

2023-05-22 06:47 UTC, bigdatasourav commented on docs/tables/azuredevops_user.md
Added the above one.

2023-05-22 06:49 UTC, bigdatasourav commented on docs/tables/azuredevops_team_member.md
Added the above.

2023-05-23 06:36 UTC, misraved commented
@bigdatasourav did we consider other authentication methods like SSH per https://learn.microsoft.com/en-us/azure/devops/repos/git/auth-overview?view=azure-devops#authentication-comparison

2023-05-23 06:53 UTC, bigdatasourav commented
@misraved As of now the [SDK](https://github.com/microsoft/azure-devops-go-api/) supports personal access token. We can always add more authentication modes once they are available in SDK.

2023-05-23 13:32 UTC, merged